default_platform(:ios)

DEVELOPER_APP_ID = ENV["DEVELOPER_APP_ID"]
DEVELOPER_APP_IDENTIFIER = ENV["DEVELOPER_APP_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]
APPLE_ISSUER_ID = ENV["APPLE_ISSUER_ID"]
APPLE_KEY_ID = ENV["APPLE_KEY_ID"]
APPLE_KEY_CONTENT = ENV["APPLE_KEY_CONTENT"]
GIT_AUTHORIZATION = ENV["GIT_AUTHORIZATION"]

platform :ios do
  desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch")
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  lane :beta do
    sync_code_signing(type: "appstore") 
    build_app(scheme: "ExampleAppCocoapod",
              workspace: "ExampleAppCocoapod/ExampleAppCocoapod.xcworkspace",
              include_bitcode: true)
    upload_to_testflight
  end

  def release(type)
    update_fastlane
    podspecName = "AdaEmbedFramework.podspec"
    ensure_git_branch
    # ensure_git_status_clean
    gym(
      skip_archive: true,
      skip_codesigning: true,
      derived_data_path: "."
    )
    zip(
      path: "Build/Products/Release-iphoneos/AdaEmbedFramework.framework",
      output_path: "AdaEmbedFramework.framework.zip"
    )
    pod_lib_lint
    version = version_get_podspec(path: podspecName)

    github_release = set_github_release(
      repository_name: "adasupport/ios-sdk",
      api_bearer: ENV["FL_GITHUB_RELEASE_API_BEARER"],
      name: "#{version}",
      tag_name: "#{version}",
      description: (File.read("changelog") rescue "No changelog provided"),
      commitish: "master",
      upload_assets: ["AdaEmbedFramework.framework.zip"]
    )
  end
end
