default_platform(:ios)

platform :ios do
  desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch")
  end

  desc "Release a new version with a minor bump_type"
  lane :minor do
    release("minor")
  end

  desc "Release a new version with a major bump_type"
  lane :major do
    release("major")
  end

  def release(type)
    update_fastlane
    podspecName = "AdaEmbedFramework.podspec"
    # ensure_git_branch
    # ensure_git_status_clean
    gym(
      skip_archive: true,
      skip_codesigning: true,
      derived_data_path: "."
    )
    zip(
      path: "Build/Products/Release-iphoneos/AdaEmbedFramework.framework",
      output_path: "AdaEmbedFramework.framework.zip"
    )
    pod_lib_lint
    version = version_bump_podspec(path: podspecName, bump_type: type)
    puts "#{version}"
    
    # git_add(path: podspecName)
    # git_commit(path: [podspecName], message: "#{version} release")
    # push_to_git_remote

    # github_release = set_github_release(
    #   repository_name: "adasupport/ios-sdk",
    #   api_token: ENV["GITHUB_TOKEN"],
    #   name: "#{version}",
    #   tag_name: "#{version}",
    #   description: (File.read("changelog") rescue "No changelog provided"),
    #   commitish: "master",
    #   upload_assets: ["AdaEmbedFramework.framework.zip"]
    # )

    # pod_push(allow_warnings: true, verbose: true)
  end
end
