default_platform(:ios)

platform :ios do
  desc "Release a new version with a patch bump_type"
  lane :patch do
    release("patch")
  end

  def release(type)
    update_fastlane
    podspecName = "AdaEmbedFramework.podspec"
    version = version_get_podspec(path: podspecName)

    github_release = set_github_release(
      repository_name: "adasupport/ios-sdk",
      api_bearer: ENV["FL_GITHUB_RELEASE_API_BEARER"],
      name: "#{version}",
      tag_name: "#{version}",
      description: (File.read("changelog") rescue "No changelog provided"),
      commitish: "master",
      upload_assets: ["AdaEmbedFramework.xcframework.zip"]
    )
  end
end
