name: Xcode Build
on:
  push:
    branches: [ ml/replace-pipeline ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Framework
        run: xcodebuild build BUILD_LIBRARY_FOR_DISTRIBUTION=YES


      - name: Copy Packages
        run: cp -r build/Release-iphoneos/AdaEmbedFramework.framework build/devices
      
      - name: Build Simulator Framework
        run: xcodebuild build -sdk iphonesimulator -arch arm64 -arch x86_64 BUILD_LIBRARY_FOR_DISTRIBUTION=YES

      - name: Remove arm64 from Binary
        run: lipo -remove arm64 build/Release-iphonesimulator/AdaEmbedFramework.framework/AdaEmbedFramework -output build/Release-iphonesimulator/AdaEmbedFramework.framework/AdaEmbedFramework

      - name: Copy Packages
        run: cp -r build/Release-iphonesimulator/AdaEmbedFramework.framework build/simulator

      - name: Prep Universal Package Folder
        run: mkdir build/universal && cp -r build/devices/ build/universal/
    
      - name: Create Universal Package
        run: lipo -create build/simulator/AdaEmbedFramework build/devices/AdaEmbedFramework -output build/universal/AdaEmbedFramework

      - name: Copy
        run: cp -r build/simulator/Modules/AdaEmbedFramework.swiftmodule/* build/universal/Modules/AdaEmbedFramework.swiftmodule/

      - name: Rename
        run: mv build/universal build/AdaEmbedFramework.framework

      - name: List
        run: ls -las

      - name: Zip
        run: zip -r build.zip build

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip