name: Xcode Build
on:
  push:
    branches: [ ml/replace-pipeline ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: mxcl/xcodebuild@v1
        with:
          platform: iOS
          action: build
          scheme: AdaEmbedFramework
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip build
      - uses: actions/upload-artifact@v3
        with:
          name: build zip
          path: build.zip