name: Xcode Build
on:
  push:
    branches: [ ml/replace-pipeline ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Framework for iPhones
        run: xcodebuild build

      - name: Build Framework for iPhone Simulator
        run: xcodebuild build -sdk iphonesimulator

      - name: Crate xcframework
        run: xcodebuild -create-xcframework -framework build/Release-iphoneos/AdaEmbedFramework.framework/ -framework build/Release-iphonesimulator/AdaEmbedFramework.framework/ -output "AdaEmbedFramework.xcframework"

      - name: List
        run: ls -las

      - name: Zip
        run: zip -r AdaEmbedFramework.xcframework.zip AdaEmbedFramework.xcframework
