name: Xcode Build
on:
  push:
    branches: [ ml/replace-pipeline ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: mxcl/xcodebuild@v1
        with:
          platform: iOS
          action: build
          scheme: AdaEmbedFramework
      - name: Zip
        run: zip -r build.zip build