name: Xcode Build
on:
  push:
    branches: [ ml/replace-pipeline ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: xcodebuild build
      - name: List
        run: ls -las
      - name: Zip
        run: zip -r build.zip build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip